---
title: Isle of Colonsay
timezone: UTC
collections:
  banners:
    title: Banners
    output: true
  places:
    title: Places
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
email: d@mcni.ch
description: A beautiful island and a welcoming community on the west coast of Scotland
baseurl: "/cholasa"
url: https://dmcnich.github.io
github_username: dmcnich
markdown: kramdown
kramdown:
  auto_ids: false
