---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _banners
  label: Slideshow Pictures
  create: all
  match: "**/*"
- type: directory
  path: _places
  label: Accomodation
  create: all
  match: "**/*"
- type: jekyll-posts
  label: News
  create: all
- type: jekyll-pages
  label: Not News
  create: all
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
